name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: base build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          command: idf.py build 2>&1 > /dev/null
          target: esp32s3
          path: "."
      - name: size without C++
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          command: idf.py size -l
          target: esp32s3
          path: "."
      - name: using <iostream>
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          command: idf.py -DTEST_IOSTREAM=1 size -l
          target: esp32s3
          path: "."
      - name: using <iostream> <string>
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4
          command: idf.py -DTEST_STRING=1 size -l
          target: esp32s3
          path: "."
